# Crash Information
AppName: HOI4 
AppVersion: Hydra v1.7.1 
SCMBranch: stable 
SCMCommit: 5a9265ee2fa09e1885e58a22d5fafd2b95dcf0d2 
SCMTimeStamp: "2019-06-24 11:51:06 +0200" 
DateTime: "2020-01-25 12:20:02" 
BuildType: Release 
Platform: Windows 
Architecture: 32-bit 
OperatingSystem: Windows 8 x86_64 
SystemLanguage: pt 
CPUModel: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 
CPUSpeed: 0 
CPUPhysicalCores: 8 
CPULogicalCores: 16 
SystemMemory: 16299 

# Application Specific Data 
"Test Data": Test Value 
